name: CI
on: [push]
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          key: cargo-cache-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo
            ./target

      - name: Check cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
